export type AdminUiLocale = 'en' | 'zh-CN';

export const ADMIN_UI_LOCALE_STORAGE_KEY = 'agentmemory.admin.uiLocale';
export const ADMIN_UI_DEFAULT_LOCALE: AdminUiLocale = 'en';

export const ADMIN_UI_TRANSLATIONS: Record<AdminUiLocale, Record<string, string>> = {
  en: {
    'meta.documentTitle': 'AgentMemory Admin Workbench',
    'locale.label': 'UI Language',
    'hero.eyebrow': 'AgentMemory Admin Workbench',
    'hero.title': 'Glass Runtime Console for Shared Agent Context',
    'hero.lead': 'Inspect runtime policy, structured state, startup context health, hybrid search behavior, and the raw observation ledger from one local-only control room.',
    'hero.currentRuntime': 'Current Runtime',
    'hero.loadingWorkbenchStatus': 'Loading workbench status...',
    'hero.workbenchNotes': 'Workbench Notes',
    'hero.workbenchNotesLead': 'Loopback-only UI. Structured state stays explicit-only. Search diagnostics expose ranking quality without changing the current search algorithm.',
    'metrics.observations': 'Observations',
    'metrics.sessions': 'Sessions',
    'metrics.projectsSeen': 'Projects Seen',
    'metrics.agentsSeen': 'Agents Seen',
    'metrics.currentStateFacts': 'Current State Facts',
    'metrics.payload': 'Payload',
    'metrics.summary': 'Summary',
    'metrics.lowSignal': 'Low-signal',
    'metrics.duplicateTitles': 'Duplicate titles',
    'policy.readTitle': 'Read Memory',
    'policy.writeTitle': 'Write Memory',
    'policy.loading': 'Loading',
    'policy.readLead': 'Controls startup context, state reads, hybrid search, and MCP read tools.',
    'policy.writeLead': 'Controls observation writes, state writes, session updates, and MCP record tools.',
    'policy.loadingCurrentState': 'Loading current state...',
    'tabs.runtime': 'Runtime',
    'tabs.projectContext': 'Project Context',
    'tabs.stateLab': 'State Lab',
    'tabs.searchDiagnostics': 'Search Diagnostics',
    'tabs.observationLedger': 'Observation Ledger',
    'runtime.section': 'Runtime',
    'runtime.title': 'Global policy, project inventory, and system posture',
    'runtime.lead': 'This view stays focused on workbench-level control: runtime gates, project coverage, and the current working surface for the rest of the panels.',
    'runtime.ready': 'Ready',
    'runtime.knownProjects': 'Known Projects',
    'runtime.knownAgents': 'Known Agents',
    'runtime.noDataYet': 'No data yet',
    'projectContext.section': 'Project Context',
    'projectContext.title': 'Curated startup context and health metrics',
    'projectContext.lead': 'Inspect the exact ProjectContextView that hook-backed agents and get_project_context rely on, plus payload and summary quality metrics.',
    'projectContext.ready': 'Ready',
    'projectContext.refresh': 'Refresh Context',
    'projectContext.noProjectSelected': 'No project selected.',
    'projectContext.currentStructuredState': 'Current Structured State',
    'projectContext.summaryBlocks': 'Summary Blocks',
    'projectContext.recentObservations': 'Recent Observations',
    'projectContext.renderedStartupView': 'Rendered Startup View',
    'projectContext.chooseProjectPrompt': 'Choose a project to inspect its current startup context.',
    'projectContext.contextReadDisabled': 'Context read is currently disabled.',
    'projectContext.summaryUnavailable': 'Summary blocks unavailable.',
    'projectContext.recentUnavailable': 'Recent observations unavailable.',
    'projectContext.noCurrentStructuredState': 'No current structured state recorded for this project.',
    'projectContext.noSummaryBlocks': 'No summary blocks available.',
    'projectContext.noRecentObservations': 'No recent observations available.',
    'projectContext.noProjectPanel': 'No project selected.',
    'projectContext.noSummaryDisplay': 'No summary blocks to display.',
    'projectContext.noRecentDisplay': 'No recent observations to display.',
    'projectContext.contextLoaded': 'Context loaded',
    'projectContext.contextDisabled': 'Context disabled',
    'projectContext.loadingContext': 'Loading context',
    'projectContext.generatedAt': 'Generated at {timestamp}',
    'projectContext.noStructuredContext': 'No structured context recorded yet.',
    'stateLab.section': 'State Lab',
    'stateLab.title': 'Inspect and explicitly write structured state facts',
    'stateLab.lead': 'The UI only performs explicit state reads and writes. It does not auto-promote observations into state candidates.',
    'stateLab.ready': 'Ready',
    'stateLab.readStateFacts': 'Read State Facts',
    'stateLab.readCurrentFacts': 'Read current facts for the selected project.',
    'stateLab.loadFacts': 'Load Facts',
    'stateLab.results': 'Results',
    'stateLab.writeStateFact': 'Write State Fact',
    'stateLab.explicitOnlyWritePath': 'Explicit-only write path.',
    'stateLab.writeButton': 'Write State Fact',
    'stateLab.chooseProjectAndLoad': 'Choose a project and load state facts.',
    'stateLab.noMatchingFacts': 'No matching state facts for the current query.',
    'stateLab.loadingFacts': 'Loading state facts',
    'stateLab.loadedFacts': 'Loaded {count} facts.',
    'stateLab.readDisabled': 'State read disabled',
    'stateLab.stateLoaded': 'State loaded',
    'stateLab.writingFact': 'Writing state fact',
    'stateLab.factWritten': 'State fact written',
    'stateLab.wroteFact': 'Wrote {factKey} at {timestamp}',
    'stateLab.chooseProjectBeforeWrite': 'Choose a project before writing state.',
    'stateLab.factKeyRequired': 'Fact key is required.',
    'stateLab.valueParseError': 'State value looks like JSON but could not be parsed.',
    'stateLab.failedWrite': 'Failed to write state fact.',
    'search.section': 'Search Diagnostics',
    'search.title': 'Expose hybrid ranking details without changing the algorithm',
    'search.lead': 'Use wide queries to observe how FTS, vector similarity, and low-signal titles affect current ranking order.',
    'search.waiting': 'Waiting for query',
    'search.runButton': 'Run Diagnostics',
    'search.statusPrompt': 'Run a query to inspect score composition.',
    'search.resultsPrompt': 'Run a query to inspect hybrid search ranking.',
    'search.metricHybrid': 'Hybrid',
    'search.metricFts': 'FTS',
    'search.metricVector': 'Vector',
    'search.metricDate': 'Date',
    'search.lowSignal': 'Low Signal',
    'search.noResults': 'No results for the current diagnostic query.',
    'search.running': 'Running diagnostics',
    'search.readyStatus': 'Diagnostics ready',
    'search.queryPrefix': 'Query: {query}',
    'search.returnedResults': 'Returned {count} results',
    'search.chooseProjectBeforeRun': 'Choose a project before running diagnostics.',
    'search.enterQueryBeforeRun': 'Enter a query before running diagnostics.',
    'search.failedToRun': 'Failed to run diagnostics.',
    'ledger.section': 'Observation Ledger',
    'ledger.title': 'Full observation browsing and detail drill-down',
    'ledger.lead': 'Keep the raw ledger as the deep inspection surface while the other panels focus on structured state, curated startup context, and hybrid search diagnostics.',
    'ledger.ready': 'Ready',
    'ledger.refresh': 'Refresh Ledger',
    'ledger.showingLatest': 'Showing latest records',
    'ledger.loadingObservations': 'Loading observations...',
    'ledger.noMatches': 'No observations matched the current filters.',
    'ledger.showingCount': 'Showing {shown} of {total} records',
    'ledger.selectedObservation': 'Selected Observation',
    'ledger.chooseRecord': 'Choose a record',
    'ledger.selectRecordPrompt': 'Select an observation from the ledger to inspect narrative, facts, concepts, and touched files.',
    'ledger.loading': 'Loading ledger',
    'ledger.refreshing': 'Refreshing ledger',
    'ledger.filtering': 'Filtering ledger',
    'ledger.polling': 'Polling ledger',
    'ledger.syncedAt': 'Synced {time}',
    'detail.narrative': 'Narrative',
    'detail.facts': 'Facts',
    'detail.concepts': 'Concepts',
    'detail.filesRead': 'Files Read',
    'detail.filesModified': 'Files Modified',
    'detail.none': 'None',
    'field.project': 'Project',
    'field.agent': 'Agent',
    'field.query': 'Query',
    'field.limit': 'Limit',
    'field.entityType': 'Entity Type',
    'field.entityKey': 'Entity Key',
    'field.factKey': 'Fact Key',
    'field.asOf': 'As Of',
    'field.value': 'Value',
    'field.effectiveAt': 'Effective At',
    'field.allProjects': 'All projects',
    'field.allAgents': 'All agents',
    'field.chooseProject': 'Choose a project',
    'placeholder.entityType': 'project / agent / service',
    'placeholder.optional': 'Optional',
    'placeholder.factKeyRequired': 'Required',
    'placeholder.asOf': '2026-06-03T09:00:00.000Z',
    'placeholder.value': 'String or JSON, e.g. "green" or {"mode":"mcp"}',
    'placeholder.effectiveAt': 'Optional ISO timestamp',
    'placeholder.searchQuery': 'e.g. structured state startup context',
    'placeholder.ledgerQuery': 'Search title, narrative, files, project, agent',
    'common.unknownTimestamp': 'Unknown timestamp',
    'common.noNarrativeAvailable': 'No narrative available.',
    'common.none': 'None',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.saving': 'Saving',
    'common.read': 'Read',
    'common.write': 'Write',
    'common.bytes': 'bytes',
    'status.policySummary': 'Read: {readState} / Write: {writeState}',
    'status.policySaving': 'Saving policy. {summary}',
    'status.pendingPolicy': 'Pending target state is shown until the worker confirms it.',
    'status.policyUpdated': 'Policy updated: {timestamp}',
    'status.readMetaEnabled': 'Agents can restore state, context, search results, and explicit read tools.',
    'status.readMetaDisabled': 'Agents cannot restore past context, state, or search results.',
    'status.writeMetaEnabled': 'Agents can write observations, sessions, and explicit state facts.',
    'status.writeMetaDisabled': 'Agents cannot record new observations, sessions, or structured state.',
    'status.savingTargetPolicy': 'Saving target policy and waiting for worker confirmation.',
    'status.workbenchReady': 'Workbench ready',
    'status.initializationFailed': 'Failed to initialize workbench.',
    'status.policySaveFailed': 'Failed to save policy.',
  },
  'zh-CN': {
    'meta.documentTitle': 'AgentMemory 管理工作台',
    'locale.label': '界面语言',
    'hero.eyebrow': 'AgentMemory 管理工作台',
    'hero.title': '共享 Agent 上下文的玻璃态运行控制台',
    'hero.lead': '在一个仅本机可访问的控制室里统一查看运行策略、结构化状态、启动上下文健康度、混合检索行为，以及原始 observation 台账。',
    'hero.currentRuntime': '当前运行态',
    'hero.loadingWorkbenchStatus': '正在加载工作台状态...',
    'hero.workbenchNotes': '工作台说明',
    'hero.workbenchNotesLead': '界面仅绑定回环地址。结构化状态保持 explicit-only。检索诊断只暴露排序质量，不修改当前算法。',
    'metrics.observations': 'Observations',
    'metrics.sessions': 'Sessions',
    'metrics.projectsSeen': '项目数',
    'metrics.agentsSeen': 'Agent 数',
    'metrics.currentStateFacts': '当前状态事实',
    'metrics.payload': '负载',
    'metrics.summary': '摘要',
    'metrics.lowSignal': '低信号',
    'metrics.duplicateTitles': '重复标题',
    'policy.readTitle': '读取记忆',
    'policy.writeTitle': '写入记忆',
    'policy.loading': '加载中',
    'policy.readLead': '控制启动上下文、状态读取、混合检索和 MCP 读取工具。',
    'policy.writeLead': '控制 observation 写入、状态写入、session 更新和 MCP 记录工具。',
    'policy.loadingCurrentState': '正在加载当前状态...',
    'tabs.runtime': '运行态',
    'tabs.projectContext': '项目上下文',
    'tabs.stateLab': '状态实验台',
    'tabs.searchDiagnostics': '检索诊断',
    'tabs.observationLedger': 'Observation 台账',
    'runtime.section': '运行态',
    'runtime.title': '全局策略、项目清单与系统姿态',
    'runtime.lead': '这个视图聚焦于工作台级别的控制：运行开关、项目覆盖面，以及其余面板依赖的当前工作面。',
    'runtime.ready': '就绪',
    'runtime.knownProjects': '已知项目',
    'runtime.knownAgents': '已知 Agent',
    'runtime.noDataYet': '暂无数据',
    'projectContext.section': '项目上下文',
    'projectContext.title': '裁剪后的启动上下文与健康度指标',
    'projectContext.lead': '查看 hook 驱动的 agent 和 get_project_context 实际依赖的 ProjectContextView，以及负载与摘要质量指标。',
    'projectContext.ready': '就绪',
    'projectContext.refresh': '刷新上下文',
    'projectContext.noProjectSelected': '尚未选择项目。',
    'projectContext.currentStructuredState': '当前结构化状态',
    'projectContext.summaryBlocks': '摘要块',
    'projectContext.recentObservations': '最近 Observations',
    'projectContext.renderedStartupView': '渲染后的启动视图',
    'projectContext.chooseProjectPrompt': '选择一个项目以查看当前启动上下文。',
    'projectContext.contextReadDisabled': '上下文读取当前已禁用。',
    'projectContext.summaryUnavailable': '摘要块不可用。',
    'projectContext.recentUnavailable': '最近 observation 不可用。',
    'projectContext.noCurrentStructuredState': '当前项目还没有记录结构化状态。',
    'projectContext.noSummaryBlocks': '暂无摘要块。',
    'projectContext.noRecentObservations': '暂无最近 observation。',
    'projectContext.noProjectPanel': '尚未选择项目。',
    'projectContext.noSummaryDisplay': '没有可显示的摘要块。',
    'projectContext.noRecentDisplay': '没有可显示的最近 observation。',
    'projectContext.contextLoaded': '上下文已加载',
    'projectContext.contextDisabled': '上下文已禁用',
    'projectContext.loadingContext': '正在加载上下文',
    'projectContext.generatedAt': '生成时间：{timestamp}',
    'projectContext.noStructuredContext': '该项目尚未记录结构化上下文。',
    'stateLab.section': '状态实验台',
    'stateLab.title': '查看并显式写入结构化状态事实',
    'stateLab.lead': '这个界面只执行显式 state 读写，不会把 observation 自动提升为 state 候选。',
    'stateLab.ready': '就绪',
    'stateLab.readStateFacts': '读取状态事实',
    'stateLab.readCurrentFacts': '读取所选项目的当前事实。',
    'stateLab.loadFacts': '加载事实',
    'stateLab.results': '结果',
    'stateLab.writeStateFact': '写入状态事实',
    'stateLab.explicitOnlyWritePath': '仅走 explicit-only 写入路径。',
    'stateLab.writeButton': '写入状态事实',
    'stateLab.chooseProjectAndLoad': '请选择项目并加载状态事实。',
    'stateLab.noMatchingFacts': '当前查询没有匹配的状态事实。',
    'stateLab.loadingFacts': '正在加载状态事实',
    'stateLab.loadedFacts': '已加载 {count} 条事实。',
    'stateLab.readDisabled': '状态读取已禁用',
    'stateLab.stateLoaded': '状态已加载',
    'stateLab.writingFact': '正在写入状态事实',
    'stateLab.factWritten': '状态事实已写入',
    'stateLab.wroteFact': '已在 {timestamp} 写入 {factKey}',
    'stateLab.chooseProjectBeforeWrite': '写入状态前请先选择项目。',
    'stateLab.factKeyRequired': 'Fact Key 为必填项。',
    'stateLab.valueParseError': 'State value 看起来像 JSON，但解析失败。',
    'stateLab.failedWrite': '写入状态事实失败。',
    'search.section': '检索诊断',
    'search.title': '暴露混合排序细节，但不改动当前算法',
    'search.lead': '用较宽的查询观察 FTS、向量相似度和低信号标题如何影响当前排序。',
    'search.waiting': '等待查询',
    'search.runButton': '运行诊断',
    'search.statusPrompt': '运行一个查询以检查分数组成。',
    'search.resultsPrompt': '运行一个查询以查看混合检索排序。',
    'search.metricHybrid': '混合',
    'search.metricFts': '全文',
    'search.metricVector': '向量',
    'search.metricDate': '日期',
    'search.lowSignal': '低信号',
    'search.noResults': '当前诊断查询没有结果。',
    'search.running': '正在运行诊断',
    'search.readyStatus': '诊断已就绪',
    'search.queryPrefix': '查询：{query}',
    'search.returnedResults': '返回 {count} 条结果',
    'search.chooseProjectBeforeRun': '运行诊断前请先选择项目。',
    'search.enterQueryBeforeRun': '运行诊断前请输入查询。',
    'search.failedToRun': '运行诊断失败。',
    'ledger.section': 'Observation 台账',
    'ledger.title': '完整 Observation 浏览与明细下钻',
    'ledger.lead': '把原始台账保留为深度检查面，其余面板则聚焦结构化状态、裁剪后的启动上下文和混合检索诊断。',
    'ledger.ready': '就绪',
    'ledger.refresh': '刷新台账',
    'ledger.showingLatest': '显示最新记录',
    'ledger.loadingObservations': '正在加载 observations...',
    'ledger.noMatches': '当前筛选条件下没有匹配的 observations。',
    'ledger.showingCount': '显示 {shown} / {total} 条记录',
    'ledger.selectedObservation': '已选 Observation',
    'ledger.chooseRecord': '选择一条记录',
    'ledger.selectRecordPrompt': '从台账中选择一条 observation，以查看 narrative、facts、concepts 和触达文件。',
    'ledger.loading': '正在加载台账',
    'ledger.refreshing': '正在刷新台账',
    'ledger.filtering': '正在筛选台账',
    'ledger.polling': '正在轮询台账',
    'ledger.syncedAt': '同步于 {time}',
    'detail.narrative': '叙述',
    'detail.facts': '事实',
    'detail.concepts': '概念',
    'detail.filesRead': '读取文件',
    'detail.filesModified': '修改文件',
    'detail.none': '无',
    'field.project': '项目',
    'field.agent': 'Agent',
    'field.query': '查询',
    'field.limit': '限制',
    'field.entityType': '实体类型',
    'field.entityKey': '实体键',
    'field.factKey': '事实键',
    'field.asOf': 'As Of',
    'field.value': '值',
    'field.effectiveAt': '生效时间',
    'field.allProjects': '全部项目',
    'field.allAgents': '全部 Agent',
    'field.chooseProject': '选择项目',
    'placeholder.entityType': 'project / agent / service',
    'placeholder.optional': '可选',
    'placeholder.factKeyRequired': '必填',
    'placeholder.asOf': '2026-06-03T09:00:00.000Z',
    'placeholder.value': '字符串或 JSON，例如 "green" 或 {"mode":"mcp"}',
    'placeholder.effectiveAt': '可选 ISO 时间戳',
    'placeholder.searchQuery': '例如 structured state startup context',
    'placeholder.ledgerQuery': '搜索标题、叙述、文件、项目、agent',
    'common.unknownTimestamp': '未知时间戳',
    'common.noNarrativeAvailable': '没有可用叙述。',
    'common.none': '无',
    'common.enabled': '已启用',
    'common.disabled': '已禁用',
    'common.saving': '保存中',
    'common.read': '读取',
    'common.write': '写入',
    'common.bytes': '字节',
    'status.policySummary': '读取：{readState} / 写入：{writeState}',
    'status.policySaving': '正在保存策略。{summary}',
    'status.pendingPolicy': '当前显示的是目标状态，等待 worker 确认。',
    'status.policyUpdated': '策略更新时间：{timestamp}',
    'status.readMetaEnabled': 'Agent 可以恢复状态、上下文、检索结果，以及显式读取工具。',
    'status.readMetaDisabled': 'Agent 不能恢复历史上下文、状态或检索结果。',
    'status.writeMetaEnabled': 'Agent 可以写入 observations、sessions 和显式结构化状态事实。',
    'status.writeMetaDisabled': 'Agent 不能记录新的 observations、sessions 或结构化状态。',
    'status.savingTargetPolicy': '正在保存目标策略，并等待 worker 确认。',
    'status.workbenchReady': '工作台已就绪',
    'status.initializationFailed': '初始化工作台失败。',
    'status.policySaveFailed': '保存策略失败。',
  },
};
